### ISSUE TITLE
Missing "this is the problem this is solving" in readme

### ISSUE THREAD

**Issue by gehring** [BuzzteeBear/OpenXR-MotionCompensation#1]
Big fan of OpenXR so naturally I was interested in learning more about this project but it was easier for me learn how to build and customize this project than figuring out what problem it was meant to address or what features it provided.

I do understand this is a project in the very early stages for an already pretty niche use case but it would still probably worth adding a couple sentences at the top of the repo's readme explaining what this is solving and what it provides. It would go a long way towards helping people like me decide if they should try it out, contribute, or even just keep an eye on the project!

**Comment by BuzzteeBear** [comment]
Thanks for the feedback. Haven't actually thought about people finding the project without having explicitly searched for it. I will add a small paragraph describing it's purpose. 

Cheers

**Comment by gehring** [comment]
Fixed by https://github.com/BuzzteeBear/OpenXR-MotionCompensation/commit/d955b00e6f361eda5e08f1c759634652fcc1bfed , thanks!
