### ISSUE TITLE
Anti Cheat Error

### ISSUE THREAD

**Issue by Embutramid** [BuzzteeBear/OpenXR-MotionCompensation#17]
Hello,

I get the following error message with the latest version. This means that iRacing cannot be started.

		- ⚠ P:\OpenXR-MotionCompensation\XR_APILAYER_NOVENDOR_motion_compensation_32.dll is outside of Program Files; this can cause issue with sandboxed MS Store games or apps, such as OpenXR Tools for Windows Mixed Reality.
		- ⚠ P:\OpenXR-MotionCompensation\XR_APILAYER_NOVENDOR_motion_compensation_32.dll does not have a trusted signature; this is very likely to cause issues with games that use anti-cheat software.

Version 0.3.5 works fine.

**Comment by BuzzteeBear** [comment]
I strongly recommend installing oxrmc into program files directory. Also there's no need to install 32-bit version to use oxrmc in iRacing.
Easiest solution is probably to uninstall and reinstall with default settings.

**Comment by BuzzteeBear** [comment]
You might have to manually unset the 32-bit checkbox upon installing, because the installer is supposed to remember the option used during last installation procedure.

**Comment by BuzzteeBear** [comment]
Btw, oxrmc's 32 bit variant shouldn't have any influence on iRacing (using an x64 executable). So the error that's keeping you from starting it up might be something else...

**Comment by Embutramid** [comment]
Looks like it's a special iRacing problem.

**Comment by fredemmott** [comment]
Re #18, the signing ~~error~~ warning does also exist for the 64-bit version, and also prevents iRacing starting:

> C:\Program Files\OpenXR-MotionCompensation\XR_APILAYER_NOVENDOR_motion_compensation.dll does not have a trusted signature; this is very likely to cause issues with games that use anti-cheat software.

This ~~error~~ warning is reported by https://github.com/fredemmott/OpenXR-API-Layers-GUI , not iRacing itself, and is not unique to iRacing.
