### ISSUE TITLE
Sign the DLLs

### ISSUE THREAD

**Issue by fredemmott** [BuzzteeBear/OpenXR-MotionCompensation#18]
This is related to #17

Most games with anti-cheat will refuse to load DLLs that are unsigned; this includes iRacing, and also games that people don't want to use OXRMC with, if the layer is enabled (even if inactive). In this case, the OpenXR loader will not simply skip the layer - it will entirely fail, so the game can not enter VR - it will stay non-VR, stall, crash, or exit depending on the game.

This does not require EV code signing, or a business/LTD/LLC/DBA/other local equivalent legal entity. My recommendations are:

- SignPath: I've not used them, but they do offer a free service for Open Source software like this: https://about.signpath.io/product/open-source
- SSL.com: not free, but on the lower end of the price scale. They're who I use without trouble, and AFAIK they've been offering *individual* (rather than corporate) certificates for longer than anyone else that still does. https://www.ssl.com/certificates/iv-code-signing/buy/
- Certum.pl: large discount for open source; used to offer it for free, but not any more. I found the company hard to communicate with. https://shop.certum.eu/open-source-code-signing.html

**Comment by fredemmott** [comment]
To clarify, this is not a requirement of the OpenXR standard or the OpenXR loader; anti-cheat software generally modifies the `LoadLibraryA()`/`LoadLibraryW()` and similar functions to add this requirement, which in turn changes the behavior of the OpenXR loader.

**Comment by BuzzteeBear** [comment]
Thank you again for your advice!
I am aware of the unsigned binary issue and will look into potential solutions.
I don't think it's an issue in iRacing as other users reported it as working fine for them. But ofc that could potentially change with any upcoming update, if the developer decides to enforce a check.

**Comment by fredemmott** [comment]
My guess is that someone who works at iRacing uses your layer, and adds it to the whitelist shortly after they update their installation of your layer; that would explain why the report you have is shortly after a new release.

again though, this doesn’t just affect sim games: if I want to play a competitive VR FPS with anti-cheat, I must entirely disable or uninstall the layer, because the issue occurs when the loader tries to load the DLL, not when it attempts to modify the game behavior. My point here isn’t “I should be able to use OXRMC in those games”, but that I shouldn’t need to enable/disable layers on a per-game basis every time I switch between them.

**Comment by zerxen** [comment]
I would like to morally support this issue here as I just realized today that I am for months saving money for a motion platform to play in VR my favorite game WarThunder (and learned today via a different xr layer from xrnecksaver's projects dlls) that the anti-cheat system in WarThunder will silently disable all XR layers that are not properly signed...

was there progress on this issue since OP? Or do we need to start a fundraiser to get it signed by a CA here?

**Comment by BuzzteeBear** [comment]
I put in some effort and made progress towards having the binaries signed. I found a certificate provider, set up a GitHub workflow to ensure code provenance and successfully tested it with a preliminary test certificate. However I'm still waiting for final approval for the production certificate.

**Comment by zerxen** [comment]
> I put in some effort and made progress towards having the binaries signed. I found a certificate provider, set up a GitHub workflow to ensure code provenance and successfully tested it with a preliminary test certificate. However I'm still waiting for final approval for the production certificate.

Many many thanks! May I ask which provider you choose? And if free/paid ? Just out of curiosity and understanding if this will be a recurring issue in future dll releases, since I assume they are signing compiled binaries.

**Comment by embrum** [comment]
I believe this issue was causing EA WRC to not launch. Uninstalling OXRMC fixed the launch issue. This started after EA implemented kernel level anti-cheat. Many thanks if you get these binaries signed!

**Comment by BuzzteeBear** [comment]
Starting with 0.3.9.0 oxrmc will be published with signed binaries
