### ISSUE TITLE
Add `VERSIONINFO` resources to DLL and exe files

### ISSUE THREAD

**Issue by fredemmott** [BuzzteeBear/OpenXR-MotionCompensation#19]
This shows up in file properties -> details, but most importantly, is included in minidumps, including ones created by games. For example, here I can easily see which version of OpenKneeboard a dump is from, and that it's a different version than the one I've got file properties open for:

![image](https://github.com/user-attachments/assets/b8a372c4-d74a-4255-b74a-19c6b5525cdb)

It would be nice if I could also check that dumps that include OXRMC weren't using an outdated version of OXRMC; adding the VERSINOINFO resource would allow that.

**Comment by BuzzteeBear** [comment]
Added version info in latest release (0.3.7)
