### ISSUE TITLE
How to run this project independently on PICO or QUEST

### ISSUE THREAD

**Issue by HexStark** [BuzzteeBear/OpenXR-MotionCompensation#23]
This is great work, and we are developing software for the all-in-one machine, and we hope to be able to run this software on the all-in-one machine to adapt it to the games on the all-in-one machine.

**Comment by BuzzteeBear** [comment]
Currently the project only runs on x86 / amd64 architecture CPUs on Microsoft Windows machines.
I assume it would require substantial effort to get it poerted to arm64 / android. But to be honest I haven't looked any closer into it, personally and I probably won't for the foreseeable future.

**Comment by BuzzteeBear** [comment]
Issue closed due to inactivity

**Comment by BuzzteeBear** [comment]
Issue closed due to inactivity
