### ISSUE TITLE
Shortcut keys are being triggered by unmapped modifiers

### ISSUE THREAD

**Issue by rosskevin** [BuzzteeBear/OpenXR-MotionCompensation#4]
Given:
```
; toggle overlay display
toggle_overlay = CTRL+D
```

Then `CTRL+SHIFT+D` is triggering the `toggle_overlay`.  I've got a massive set of hot key mappings de-conflicted and I've got others being triggered or intercepted altogether.  Caching, and I think save config is also getting caught (and not bubbling).  Several controls on my motion controls are affected.

Here's a sample of my de-conflicted mappings as some general context: https://docs.google.com/spreadsheets/d/15N_efoa97qZxECsUiLlXfGdGy4MXqk-q/edit?usp=sharing&ouid=113445743503697882083&rtpof=true&sd=true

**Comment by rosskevin** [comment]
I mentioned this on discord, but for completeness sake, the modifiers I see in use are:
- ctrl
- alt
- shift
- numlock? e.g. `kp 0` or `keypad 0` as seen in iracing

I assume caps lock is triggered as a shift.

**Comment by BuzzteeBear** [comment]
Feature to exclude key combination when additional modifiers are included (ctrl, shift. alt) has been added with this [commit](https://github.com/BuzzteeBear/OpenXR-MotionCompensation/commit/598a7247d5478156f413343303301df5d493abc9)
Note that it will not work properly for manual keyboard input.
