### ISSUE TITLE
open xr motioncompensation 

### ISSUE THREAD

**Issue by KentN53** [BuzzteeBear/OpenXR-MotionCompensation#7]
Hello!

When I try to initiate motioncompensation in FS2020 VR the voice say "Error" what might be wrong?

rgds
Kent

**Comment by BuzzteeBear** [comment]
Hi Kent,

that's impossible to tell, based on that little information. 
First step should be to check the log file (C:/Users/.../appdata/local/OpenXR-MotionCompensation/OpenXR-MotionCompensation.log) for error entries. That should give you an idea of what's going wrong...

Regards,

Sebastian

**Comment by KentN53** [comment]
Thank you for your responsen! I just found the problem in the ini filé. It
is not fixad!

Rgds

Kent t

Den tors 30 nov. 2023 12:22Sebastian Veith ***@***.***> skrev:

> Hi Kent,
>
> that's impossible to tell, based on that little information.
> First step should be to check the log file
> (C:/Users/.../appdata/local/OpenXR-MotionCompensation/OpenXR-MotionCompensation.log)
> for error entries. That should give you an idea of what's going wrong...
>
> Regards,
>
> Sebastian
>
>
